nfq_weather:
   provider: delegating
   providers:
       openweathermap:
           api_key: 'bbeb1d7d8008048e3127c52f30a22539'
       delegating:
           providers:
               - yahoo
               - openweathermap
